### ISSUE TITLE
parser data doesn't seem to accept h.getArg

### ISSUE THREAD

**Issue by belgac** [dchrzanowski/mtml#5] opened 2018-10-11 16:00 UTC
Hi,

I'm trying to use the entity parser. When I provide h.getArg(1) to the data key of the parser it doesn't seem to work and returns `File read error: Error: ENOENT: no such file or directory, open '/projects/private/packages/style-atoms/h.getArg(1)'` with this entity configuration:
```
{
  "entity": {
    "parser": {
      "file": "./scripts/dimensionParser",
      "data": "h.getArg(1)"
    }
}
```
is the data key not parsed by mtml?

**Comment by dchrzanowski** [comment] 2018-10-11 16:11
Yes `mtml` does not parse the `file` or the `data` key. Working on the fix now.

**Comment by dchrzanowski** [comment] 2018-10-11 16:23
I'm sorry @belgac but I already published the fix, before I saw the PR.

Anyway this is now fixed and works as intended. Thank you very much for catching this error!!!

**Closed as completed by dchrzanowski** 2018-10-11 16:23 UTC
